NanozITSH/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'NanozITSH.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^noSoy1admin/', include(admin.site.urls)),
    url(r'^', include('apps.index.urls', namespace='index_app')),
    url(r'^login/$', 'apps.usuarios.views.loginUsuario', name='login'),
    url(r'^registrar_oferta/$', 'apps.ofertas.views.nuevaOferta', name='OfertaNueva'),
    url(r'^salir/$', 'apps.usuarios.views.salir', name='salir'),
    url(r'^registro/$', 'apps.usuarios.views.registro', name='registro'),
    url(r'^acercaDe/$', 'apps.usuarios.views.acercaDe', name='acercaDe'),
    url(r'^egresados/$', 'apps.ofertas.views.Egresados', name='egresados'),
    url(r'^Oferta/$', 'apps.ofertas.views.detalleOferta', name='oferta'),
    #url(r'^test/$', 'apps.usuarios.views.test1', name='test'),
    url(r'^test/$', 'apps.usuarios.views.testDinamico', name='test2'),
    url(r'^terminos-y-condiciones/$', 'apps.usuarios.views.UsosYCondiciones', name='UsosYCondiciones'),

]
urlpatterns += patterns('', (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    'document_root': settings.MEDIA_ROOT}))

apps/index/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'apps.index.views.home', name='index'),
    url(r'^test$', 'apps.index.views.test', name='test'),
]

apps/usuarios/models.py
from datetime import date
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


class UserManager(BaseUserManager, models.Manager):
    def _create_user(self, username, email, password, is_staff, is_superuser, is_active=False, **extra_fields):
        email = self.normalize_email(email)

        user = self.model(username=username, email=email, is_active=is_active,
                          is_staff=is_staff, is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, is_active=True, **extra_fields):
        # print('creando usuario')
        return self._create_user(username, email, password, False, False, is_active=True, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True, is_active=True, **extra_fields)


def listaAnos():
    anoFin = (date.today().year) - 4
    anoInicio = 2001
    lista = []
    while (anoInicio < anoFin):
        otroAno = anoInicio + 4
        fecha = str(anoInicio) + " - " + str(otroAno)
        lista.append((fecha, fecha))
        anoInicio += 1
    return lista


class Carrera(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    def __unicode__(self):
        return self.nombre


class Modalidad(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    def __unicode__(self):
        return self.nombre


class Usuario(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=40, unique=True)
    nombre = models.CharField(max_length=40, blank=True)
    apellidos = models.CharField(max_length=40, blank=True)
    matricula = models.CharField(max_length=10, blank=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(unique=True)
    status = models.BooleanField(default=False)  # para validar al usuario
    carreraEgreso = models.IntegerField(default=0)
    anoEgreso = models.CharField(max_length=20, choices=listaAnos())
    objects = UserManager()
    sexo = models.CharField(max_length=10)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    @property
    def get_short_name(self):
        if self.nombre != "":
            return self.nombre + self.matricula
        elif self.username != "":
            return self.username + self.matricula
        else:
            return self.email + self.matricula

    @property
    def get_full_name(self):
        if self.nombre != "":
            return self.nombre + " " + self.apellidos
        elif self.username != "":
            return self.username
        else:
            return str(self.email)

    def __str__(self):
        return self.get_short_name

    def __unicode__(self):
        return self.get_short_name


class Creditos(models.Model):
    usuario = models.ForeignKey(Usuario)
    cantidad = models.IntegerField(default=0)


class Egresado(models.Model):
    nombre = models.CharField(max_length=100, default="")
    apellidos = models.CharField(max_length=100, default="")
    num_control = models.CharField(max_length=100, default="")
    telefono = models.CharField(max_length=20, blank=True, null=True)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    sexos = (("H", "H"), ("M", "M"))
    sexo = models.CharField(max_length=1, choices=sexos)
    # direccion = models.ForeignKey(Direccion, blank=True, null=True)


class Direccion(models.Model):
    calle = models.CharField(max_length=40)
    colonia = models.CharField(max_length=40)
    codigo_postañ = models.CharField(max_length=5)


class Pertenece(models.Model):
    egresado = models.ForeignKey(Egresado)
    carrera = models.ForeignKey(Carrera)
    modalidad = models.ForeignKey(Modalidad)

apps/usuarios/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from apps.usuarios.models import Usuario


class FormCrearUsuario(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password')
        widgets = {
            'username': forms.TextInput(attrs={
                #'class': 'form-control',
                'required': 'true',
            }),
            'email': forms.EmailInput(attrs={
                'type': 'email',
                #'class': 'form-control',
                'required': 'true',
            }),
            'password': forms.TextInput(attrs={
                'type': 'password',
                #'class': 'form-control psw',
                'required': 'true',
            }),
        }
        labels = {
            'username': _("Nombre de usuario"),
            'email': _("Correo Electronico"),
            'password': _("Contraseña"),
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        usuario = True
        correo = True
        if len(cleaned_data.get("username")) < 4:
            self._errors['username'] = self.error_class(["El nombre de usuario debe contener mínimo 4 caracteres"])
            usuario = False
        if len(cleaned_data.get("password")) < 6:
            self._errors['password'] = self.error_class(["La contraseña debe contener mínimo 6 caracteres"])
        if Usuario.objects.filter(username=cleaned_data.get("username").lower().strip().replace(' ', '_')):
            # print("El nombre de usuario ya esta en uso")
            self._errors['username'] = self.error_class(["El nombre de usuario ya esta en uso"])
            usuario = False

        if usuario and correo:
            return cleaned_data

    def __init__(self, *args, **kwargs):
        super(FormCrearUsuario, self).__init__(*args, **kwargs)
        self.fields['username'].required = True
        self.fields['email'].required = True
        self.fields['password'].required = True

apps/usuarios/views.py
from datetime import date

from django.contrib.auth import login, logout
from django.shortcuts import render, redirect

from apps.documentos.models import FormularioResidencias, Cuestionario, Respuesta
from apps.usuarios.forms import FormCrearUsuario
from apps.usuarios.models import Carrera, Usuario
from django.core.urlresolvers import reverse


def CreacionUsuarios(request):
    formCreacion = FormCrearUsuario()
    return render(request, 'index/login.html', {
        'formCreacion': formCreacion
    })


def listaAnos():
    anoFin = (date.today().year) - 4
    anoInicio = 2001
    lista = []
    while (anoInicio < anoFin):
        otroAno = anoInicio + 4
        fecha = str(anoInicio) + " - " + str(otroAno)
        lista.append(fecha)
        anoInicio += 1
    return lista


def salir(request):
    logout(request)
    return render(request, 'index/index.html')


def loginUsuario(request):
    if request.method == "POST":
        if "username" in request.POST and "password" in request.POST:
            users = Usuario.objects.filter(email=request.POST["username"])
            if users.exists():
                password = users[0].check_password(str(request.POST["password"]))
                if password:
                    user = users[0]
                    user.backend = 'django.contrib.auth.backends.ModelBackend'
                    login(request, user)
                    return redirect(reverse('egresados'))
            return render(request, "index/login.html", {'error': "Usuario o contraseña mal"})
    return render(request, "index/login.html")


def registro(request):
    error = None
    if request.user.is_authenticated():
        return redirect(reverse('egresados'))
    if request.method == "POST":
        try:
            matricula = str(request.POST['matricula']).strip()
            indice = int(matricula[:2])
            zeta = matricula[3:4].lower()
            anio = date.today().year - 2000
            if indice < anio and zeta == "z":
                carrera = Carrera.objects.get(nombre=request.POST["carrera"])
                user = Usuario.objects.create(
                        username=str(request.POST["email"]).strip(),
                        nombre=str(request.POST["name"]).strip(),
                        apellidos=(str(request.POST["apellidop"]) + " " + str(request.POST["apellidom"])).strip(),
                        email=str(request.POST["email"]).strip(),
                        matricula=matricula,
                        carreraEgreso=carrera.id,
                        sexo=request.POST["sexo"],
                        password=str(request.POST["Pass1"])
                )
                user.set_password(request.POST["Pass1"])
                user.save()
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(request, user)
                return redirect(reverse('egresados'))
            else:
                error = "matricula no valida"
        except:
            error = "matricula no valida"
    carreras = Carrera.objects.all()
    return render(request, 'index/loginV2.html', {
        'carreras': carreras,
        'error': error,
        'años': listaAnos()
    })


def acercaDe(request):
    return render(request, 'index/acercaDe.html')


def UsosYCondiciones(request):
    return render(request, 'UsusYCondiciones.html')


def test1(request):
    user = request.user
    error = None
    if not user.is_authenticated():
        return redirect(reverse('login'))
    if request.method == "POST":
        try:
            user = request.user
            FormularioResidencias.objects.create(
                    usuario=user,
                    residencias=request.POST['RESIDENCIAS'],
                    domicilioActual=request.POST['DOMICILIO'],
                    telefono=request.POST['TELEFONO'],
                    empleoActual=request.POST['EMPLEO_ACTUAL'],
                    enfoqueEmpleo=int(request.POST['ENFOQUE']),
                    pregunta1=int(request.POST['NIVEL']),
                    pregunta2=request.POST['NECESIDADES'],
                    pregunta3=int(request.POST['ZONA']),
                    pregunta4=request.POST['NO_ENCONTRADO'],
                    pregunta5=request.POST['DIFICULTADES'],
                    pregunta6=int(request.POST['OP_POSGRADO']),
                    pregunta7=request.POST['PORQUE'],
                    pregunta8=int(request.POST['FORO']),
                    pregunta9=request.POST['SUGERENCIA'],
                    pregunta10=int(request.POST['FORMACION']),
            )
            user.status = True
            user.save()
            return redirect(reverse('egresados'))
        except Exception as e:
            error = e
    carreras = Carrera.objects.all()
    return render(request, 'usuarios/test1.html', {
        "carreras": carreras,
        "error": error,
        'anios': listaAnos()
    })


def testDinamico(request):
    print(request.POST)
    print(request.GET)
    print(request.FILES)
    user = request.user
    error = None
    cuestionario = Cuestionario.objects.filter(activo=True)[0]
    preguntas = cuestionario.listado.all()
    if not user.is_authenticated():
        return redirect(reverse('login'))
    if request.method == "POST":
        try:
            user.status = True
            user.save()
            for pregunta in preguntas:
                respuesta = Respuesta.objects.create(
                        usuario=user,
                        cuestionario=cuestionario.id,
                        pregunta=pregunta,
                )
                if pregunta.tipo == 1:
                    respuesta.texto = request.POST[str(pregunta.id)]
                if pregunta.tipo == 2:
                    value = request.POST[str(pregunta.id)]
                    if value == "1" or value == 1:
                        respuesta.si_no = 1
                    else:
                        respuesta.si_no = 2
                if pregunta.tipo == 3:
                    respuesta.imagen = request.FILES[str(pregunta.id)]
                if pregunta.tipo == 4:
                    respuesta.textos = request.POST[str(pregunta.id)]
                pregunta.save()
        except Exception as e:
            print(e.args)
        return redirect(reverse('egresados'))
    carreras = Carrera.objects.all()
    return render(request, 'usuarios/testDinamico.html', {
        "carreras": carreras,
        "preguntas": preguntas,
        "error": error,
        'anios': listaAnos()
    })

templates/usuarios/testDinamico.html
{% load static %}
<!DOCTYPE HTML>

<html>
<head>
    <title>FORMULARIO</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="{% static 'index/assets/css/main.css' %}"/>
    <!--[if lte IE 8]><link rel="stylesheet" href="{% static 'index/assets/css/ie8.css'%}" /><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="{% static 'index/assets/css/ie9.css'%}" /><![endif]-->
</head>
<body>

<!-- Page Wrapper -->
<div id="page-wrapper">

    <!-- Header -->
    <header id="header">
        <h1><a href="{% url 'index_app:index' %}">Inicio</a></h1>
        <nav id="nav">
            <ul>
                <li class="special">
                    <a href="#menu" class="menuToggle"><span>Menu</span></a>
                    <div id="menu">
                        <ul>
                            <li><a href="{% url 'index_app:index' %}">Inicio</a></li>
                            <li><a href="{% url 'egresados' %}">Egresados</a></li>
                            <li><a href="{% url 'acercaDe' %}">Acerca de</a></li>
                            {% if user.is_authenticated %}
                                <li>Hola {{ user.nombre }}</li>
                                <li><a href="{% url 'salir' %}">Salir</a></li>
                            {% else %}
                                <li><a href="{% url 'login' %}">Ingresa</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </li>
            </ul>
        </nav>
    </header>

    <!-- Main -->
    <article id="main">
        <header>
            <h2>FORMULARIO DE SEGUIMIENTO</h2>
            <p>Llena el siguiente formulario para dar seguimiento a tu profesion</p>
        </header>
        <section class="wrapper style5">
            <div class="inner">
                <section>
                    <h4>LLENA EL TEST PARA PODER VER LAS OFERTAS</h4>
                    <p align="justify">
                        Este es el seguimiento de egresados del Instituo Tecnológico Superior de Huatusco, aquí podrás
                        llenar un test, elaborado por el personal del instituto, con la finalidad de, ayudarte a tí como
                        egresado del ITSH a posicionarte en una empresa o institución adecuada a tu perfil académico,
                        anexando tus datos que se han ido recabando desde que acudiste a tu servicio social.
                    </p>

                    <p align="justify">
                        Recuerda que el ITSH te apoya en todo momento, el Sistema de Seguimieto te otorga un curriculum
                        con la informacion profesional que adquiere el egresado desde sus practicas de servicio social,
                        practicas de residencia profesional y tu empleo actual, cuya informacion deberás llenar a
                        continuación:
                    </p>
                    <form method="post" action="{% url 'test2' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if error %}
                            <h3 class="text-danger">{{ error }}</h3>
                        {% endif %}
                        <div class="row uniform">
                            {% for pregunta in preguntas %}
                                <div class="12u$">
                                    <label for="{{ pregunta.id }}">{{ pregunta.texto }}</label>
                                    {% if pregunta.tipo == 1 %}
                                        <input type="text" name="{{ pregunta.id }}" id="{{ pregunta.id }}" required/>
                                    {% endif %}
                                    {% if pregunta.tipo == 2 %}
                                        <div class="select-wrapper">
                                            <select name="{{ pregunta.id }}" id="{{ pregunta.id }}">
                                                <option value="1">SI</option>
                                                <option value="2">NO</option>
                                            </select>
                                        </div>
                                    {% endif %}
                                    {% if pregunta.tipo == 3 %}
                                        <input type="file" name="{{ pregunta.id }}" id="{{ pregunta.id }}" required/>
                                    {% endif %}
                                    {% if pregunta.tipo == 4 %}
                                        <input type="text" name="{{ pregunta.id }}" id="{{ pregunta.id }}" required/>
                                    {% endif %}
                                </div>
                            {% endfor %}
                            <div class="12u$">
                                <ul class="actions">
                                    <li><input type="submit" value="ENVIAR TEST" class="special"/></li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </section>
    </article>
</div>

<!-- Scripts -->
<script src="{% static 'index/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'index/assets/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'index/assets/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'index/assets/js/skel.min.js' %}"></script>
<script src="{% static 'index/assets/js/util.js' %}"></script>
<!--[if lte IE 8]><script src="{% static 'index/assets/js/ie/respond.min.js'%}"></script><![endif]-->
<script src="{% static 'index/assets/js/main.js' %}"></script>

</body>
</html>